---
- name: Check the filebeat version if its already installed
  set_fact:
    filebeat_installed_version: "{{ansible_facts.packages['filebeat'][0].version}}"
  when: "ansible_facts.packages is defined and 'filebeat' in ansible_facts.packages and (ansible_facts.packages['filebeat'] | length) == 1"
  tags:
   - default

- name: Remove filebeat package if it does not match the version which is being installed
  apt:
    name: filebeat
    state: absent
  when: filebeat_installed_version is defined and filebeat_installed_version != filebeat_version
  tags:
   - default

- name: Remove filebeat registry directory if it does not match the version which is being installed
  file: 
    path: /var/lib/filebeat/registry
    state: absent
  when: filebeat_installed_version is defined and filebeat_installed_version != filebeat_version
  tags:
   - default

- name: Stop filebeat
  systemd:
    name: filebeat
    state: stopped
  tags:
   - stop-filebeat

- name: Start filebeat
  systemd:
    name: filebeat
    state: started
  tags:
   - start-filebeat
