---

- name: set fact force_install to no
  set_fact: force_install=no

- name: set fact force_install to yes
  set_fact: force_install=yes
  when: es_allow_downgrades

- name: Debian - Install apt-transport-https to support https APT downloads
  become: yes
  apt: name=apt-transport-https state=present
  when: es_use_repository

- name: Debian - Add Elasticsearch repository key
  become: yes
  apt_key: url="{{ es_apt_key }}" state=present
  when: es_use_repository and es_apt_key

- name: Debian - Add elasticsearch repository
  become: yes
  apt_repository: repo={{ item.repo }} state={{ item.state}}
  with_items:
    - { repo: "{{ es_apt_url_old }}", state: "absent" }
    - { repo: "{{ es_apt_url }}", state: "present" }
  when: es_use_repository

- name: Debian - Include versionlock
  include: elasticsearch-Debian-version-lock.yml
  when: es_version_lock
